message: This is a message defined in the configuration file config.yaml.
database:
   driverClass: com.mysql.jdbc.Driver
   user: recipe
   password: recipepassword
   url: jdbc:mysql://legion.pariah.local/myhome
