apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /target/mariadb

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    selector: mariadb
spec:
  restartPolicy: Never
  volumes:
    - name: vol
      hostPath:
        path: /target/mariadb
  containers:
    - name: mariadb
      image: mariadb:latest
      #command: ['ps -ef']
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: vol
          mountPath: /mariadb
      args:
        - sleep
        - "1000000"

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    #app: mariahdb
    #branch: $GIT_BRANCH
    #environment: staging
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      protocol: TCP
      name: mariadb
  selector:
    app: mariadb
    #branch: $GIT_BRANCH
#environment: staging