apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
    - name: db
      image: mariadb:latest
      args:
        - sleep
        - "1000000"
---
apiVersion: v1
kind: Pod
metadata:
  name: java
spec:
  containers:
    - name: java
      image: openjdk:8-jre
      args:
        - sleep
        - "1000"