apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /target/mariadb

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: mariadb
#  labels:
#    selector: mariadb
#spec:
#  restartPolicy: Never
#  volumes:
#    - name: vol
#      hostPath:
#        path: /target/mariadb
#  containers:
#    - name: mariadb
#      image: mariadb:latest
#      #command: ['ps -ef']
#      ports:
#        - containerPort: 3306
#      volumeMounts:
#        - name: vol
#          mountPath: /mariadb
#      args:
#        - sleep
#        - "1000000"

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      protocol: TCP
      name: mariadb
      targetPort: 3306
  selector:
    app: mariadb
    #branch: $GIT_BRANCH
#environment: staging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      run: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        run: mariadb
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /target/mariadb
      containers:
        - name: mariaddb
          image: mariadb:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: vol
              mountPath: /mariadb
