---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  selector:
    matchLabels:
      run: java
  replicas: 1
  template:
    metadata:
      labels:
        run: java
    spec:
      volumes:
        - name: java
          hostPath:
            path: /target
      containers:
        - name: java
          image: openjdk:8-jre
          command: ['java -jar ./target/myHome-1.0-SNAPSHOT.jar server ./config.yaml']
          ports:
            - containerPort: 443
          volumeMounts:
            - name: vol
                mountPath: /java
          args:
            - sleep
            - "1000000"